version: '3'

services:
  web-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  web-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: web-proxy-letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  enstaved-www:
    build:
      context: ./www
    container_name: enstaved-www
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - VIRTUAL_HOST=enstaved.com,www.enstaved.com
      - LETSENCRYPT_HOST=enstaved.com,www.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
  enstaved-gallery:
    image: kdelfour/lychee-mysql-docker
    container_name: enstaved-gallery
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - VIRTUAL_HOST=gallery.enstaved.com
      - LETSENCRYPT_HOST=gallery.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
    volumes:
      - enstaved-gallery-uploads/:/uploads/
      - enstaved-gallery-data/:/data/
      - enstaved-gallery-plugins/:/plugins/
    links:
      - enstaved-gallery-db:mysql
  enstaved-gallery-db:
    image: mysql:5.7
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - enstaved-gallery-db:/var/lib/mysql
  enstaved-survey:
    image: crramirez/limesurvey:latest
    container_name: enstaved-survey
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - VIRTUAL_HOST=survey.enstaved.com
      - LETSENCRYPT_HOST=survey.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
    volumes:
      - enstaved-survey-data/:/var/lib/mysql
      - enstaved-survey-uploads/:/app/upload
  enstaved-hieronymus:
    build:
      context: ./hieronymus
    container_name: enstaved-hieronymus
    restart: unless-stopped
    ports:
      - "8003:80"
    environment:
      - VIRTUAL_HOST=hieronymus.enstaved.com
      - LETSENCRYPT_HOST=hieronymus.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
    volumes:
      - enstaved-hieronymus-models/:/data/models

volumes:
  proxy-certs:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/www-proxy/certs
  proxy-vhosts:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/www-proxy/vhosts
  proxy-html:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/www-proxy/html
  enstaved-gallery-uploads:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/uploads
  enstaved-gallery-data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/data
  enstaved-gallery-plugins:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/plugins
  enstaved-gallery-db:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/db
  enstaved-survey-uploads:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-survey/uploads
  enstaved-survey-data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-survey/data
  enstaved-hieronymus-models:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-hieronymus/models
