version: '3'

services:
  web-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  web-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: web-proxy-letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  enstaved-www:
    build:
      context: ./www
    container_name: enstaved-www
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      # We need a cert for mail.enstaved.com to use in the enstaved-mail
      # service. The web-proxy-letsencrypt service automatically creates
      # wildcard certs for multiple sub-domains of the same domain, using
      # the first domain in the list as the "primary". The automagic
      # letsencrypt detection in enstaved-mail looks for a directory with
      # the email subdomain. Hence mail.enstaved.com must be first here.
      - VIRTUAL_HOST=mail.enstaved.com,www.enstaved.com
      - LETSENCRYPT_HOST=mail.enstaved.com,www.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
  enstaved-gallery:
    image: kdelfour/lychee-mysql-docker
    container_name: enstaved-gallery
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - VIRTUAL_HOST=gallery.enstaved.com
      - LETSENCRYPT_HOST=gallery.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
    volumes:
      - enstaved-gallery-uploads/:/uploads/
      - enstaved-gallery-data/:/data/
      - enstaved-gallery-plugins/:/plugins/
    links:
      - enstaved-gallery-db:mysql
  enstaved-gallery-db:
    image: mysql:5.7
    container_name: enstaved-gallery-db
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - enstaved-gallery-db:/var/lib/mysql
  enstaved-survey:
    image: crramirez/limesurvey:latest
    container_name: enstaved-survey
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - VIRTUAL_HOST=survey.enstaved.com
      - LETSENCRYPT_HOST=survey.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
    volumes:
      - enstaved-survey-data/:/var/lib/mysql
      - enstaved-survey-uploads/:/app/upload
  enstaved-hieronymus:
    build:
      context: ./hieronymus
    container_name: enstaved-hieronymus
    restart: unless-stopped
    ports:
      - "8003:80"
    environment:
      - VIRTUAL_HOST=hieronymus.enstaved.com
      - LETSENCRYPT_HOST=hieronymus.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
    volumes:
      - enstaved-hieronymus-models/:/data/models
  enstaved-mail:
    image: tvial/docker-mailserver:latest
    container_name: enstaved-mail
    hostname: mail
    domainname: enstaved.com
    restart: unless-stopped
    ports:
    - "25:25"
    - "110:110"
    - "143:143"
    - "587:587"
    - "993:993"
    - "995:995"
    volumes:
    - enstaved-mail-data:/var/mail
    - enstaved-mail-state:/var/mail-state
    - enstaved-mail-config:/tmp/docker-mailserver
    - proxy-certs:/etc/letsencrypt/live:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ENABLE_POP3=1
    - SSL_TYPE=letsencrypt
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
  enstaved-shop:
    build:
      context: ./shop
    container_name: enstaved-shop
    restart: unless-stopped
    ports:
      - "8004:80"
    environment:
      - VIRTUAL_HOST=shop.enstaved.com
      - LETSENCRYPT_HOST=shop.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
      - PORT=80
      - ALLOWED_HOSTS=shop.enstaved.com
      - DATABASE_URL=postgres://${SHOP_DB_USER}:${SHOP_DB_PASSWORD}@postgres/${SHOP_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/${SHOP_REDIS}
      - EMAIL_URL=smtps://${SHOP_EMAIL_USER}:${SHOP_EMAIL_PASSWORD}@${SHOP_EMAIL_HOST}:${SHOP_EMAIL_PORT}
      - SECRET_KEY=${SHOP_SECRET_KEY}
      - DEBUG=False
      - DEFAULT_FROM_EMAIL="admin@enstaved.com"
      - GOOGLE_ANALYTICS_TRACKING_ID=${SHOP_GOOGLE_ANALYTICS}
      - STRIPE_SECRET_KEY=${SHOP_STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${SHOP_STRIPE_PUBLIC_KEY}
    volumes:
      - enstaved-shop-media:/media
    links:
      - enstaved-postgres:postgres
      - enstaved-redis:redis
  enstaved-devshop:
    build:
      context: ./devshop
    container_name: enstaved-devshop
    restart: unless-stopped
    ports:
      - "8005:80"
    environment:
      - VIRTUAL_HOST=devshop.enstaved.com
      - LETSENCRYPT_HOST=devshop.enstaved.com
      - LETSENCRYPT_EMAIL=admin@enstaved.com
      - PORT=80
      - ALLOWED_HOSTS=devshop.enstaved.com
      - DATABASE_URL=postgres://${DEVSHOP_DB_USER}:${DEVSHOP_DB_PASSWORD}@postgres/${DEVSHOP_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/${DEVSHOP_REDIS}
      - EMAIL_URL=smtps://${DEVSHOP_EMAIL_USER}:${DEVSHOP_EMAIL_PASSWORD}@${DEVSHOP_EMAIL_HOST}:${DEVSHOP_EMAIL_PORT}
      - SECRET_KEY=${DEVSHOP_SECRET_KEY}
      - DEBUG=True
      - DEFAULT_FROM_EMAIL="admin@enstaved.com"
      - GOOGLE_ANALYTICS_TRACKING_ID=${DEVSHOP_GOOGLE_ANALYTICS}
      - STRIPE_SECRET_KEY=${DEVSHOP_STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${DEVSHOP_STRIPE_PUBLIC_KEY}
    volumes:
      - enstaved-devshop-media:/media
    links:
      - enstaved-postgres:postgres
      - enstaved-redis:redis
  enstaved-postgres:
    build:
      context: ./postgres
    container_name: enstaved-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SHOP_DB
      - SHOP_DB_USER
      - SHOP_DB_PASSWORD
      - DEVSHOP_DB
      - DEVSHOP_DB_USER
      - DEVSHOP_DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - enstaved-postgres-db:/var/lib/postgresql/data/pgdata
  enstaved-redis:
    image: 'bitnami/redis:latest'
    container_name: enstaved-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD
    volumes:
      - enstaved-redis-db:/bitnami

volumes:
  proxy-certs:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/www-proxy/certs
  proxy-vhosts:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/www-proxy/vhosts
  proxy-html:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/www-proxy/html
  enstaved-gallery-uploads:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/uploads
  enstaved-gallery-data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/data
  enstaved-gallery-plugins:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/plugins
  enstaved-gallery-db:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-gallery/db
  enstaved-survey-uploads:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-survey/uploads
  enstaved-survey-data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-survey/data
  enstaved-hieronymus-models:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-hieronymus/models
  enstaved-mail-data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/mail/data
  enstaved-mail-state:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/mail/state
  enstaved-mail-config:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/mail/config
  enstaved-shop-media:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-shop/media
  enstaved-devshop-media:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-shop/media
  enstaved-postgres-db:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-postgres/db
  enstaved-redis-db:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/enstaved-redis/db
